fact = [0 0 1];
for t = 9:-1:0
    for e = 9:-1:0
        if t > 0 || e > 0
            fact = mul_int([t e], fact);
        end
    end
end

fprintf('factorial  = %s.%s%s%s%se+%s\n', ...
        num2str(fact(end)), ...
        num2str(fact(end-1)), ...
        num2str(fact(end-2)), ...
        num2str(fact(end-3)), ...
        num2str(fact(end-4)), ...
        num2str(length(fact)-1));
fprintf('gamma(101) = %s\n', num2str(gamma(101),5));
